image: node:16

stages:
  - install
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install

run_tests:
  stage: test
  script:
    - npx playwright install --with-deps
    - export CORRECT_PASSWORD=secret_sauce
    - export INCORRECT_PASSWORD=incorrectPassword
    - npx playwright test
  artifacts:
    when: always
    reports:
      junit: results.xml
    paths:
      - test-results/
