image: mcr.microsoft.com/playwright:focal

stages:
  - install
  - test

install_dependencies:
  stage: install
  script:
    - npm install

run_tests:
  stage: test
  script:
    - npm install @playwright/test 
    - npx playwright install
    - export INCORRECT_PASSWORD=incorrectPassword
    - export CORRECT_PASSWORD=secret_sauce
    - npx playwright test
  artifacts:
    when: always
    reports:
      junit: results.xml
    paths:
      - test-results/

