stages:
  - add_password_variables
  - run_tests

add password variables:
  stage: add_password_variables
  script:
   - export CORRECT_PASSWORD=secret_sauce
   - export INCORRECT_PASSWORD=incorrectPassword
 rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "trigger"
      allow_failure: false

run tests:
  stage: run_tests
  script:
   - yarn playwright test
 rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "trigger"
      allow_failure: true

