stages:
  - add_password_variables
  - run_tests

add_password_variables:
  stage: add_password_variables
  script:
   - export CORRECT_PASSWORD=secret_sauce
   - export INCORRECT_PASSWORD=incorrectPassword
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
      allow_failure: false

run_tests:
  stage: run_tests
  script:
   - npm install --global yarn
   - yarn playwright test
  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
      allow_failure: true

