name: Playwright CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright library
      run: npm install @playwright/test

    - name: Install missing dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 \
          libopus0 \
          libvpx5 \
          libevent-2.1-7 \
          libfontconfig1 \
          libfreetype6 \
          libjpeg-turbo8 \
          libpng16-16 \
          libffi7 \
          libnss3 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxi6 \
          libgl1 \
          libxrender1 \
          libxrandr2 \
          libxtst6 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libatspi2.0-0 \
          libdrm2 \
          libdbus-1-3 \
          libgbm1 \
          libnspr4 \
          libpango-1.0-0 \
          libwayland-client0 \
          libwayland-cursor0 \
          libwayland-egl1 \
          libxkbcommon0 \
          libxshmfence1 \
          libegl1 \
          libgstreamer1.0-0 \
          libgstreamer-plugins-base1.0-0

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Export incorrect password
      run: echo "INCORRECT_PASSWORD=incorrectPassword" >> $GITHUB_ENV

    - name: Export correct password
      run: echo "CORRECT_PASSWORD=secret_sauce" >> $GITHUB_ENV

    - name: Run Playwright tests
      run: npx playwright test
      env:
        CORRECT_PASSWORD: ${{ env.CORRECT_PASSWORD }}
        INCORRECT_PASSWORD: ${{ env.INCORRECT_PASSWORD }}
