image: mcr.microsoft.com/playwright:focal
name: install

on: push

jobs:
  installing:
    runs-on: ubuntu-latest
    steps:
      - name: installing name
        run: npm install
  test:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run:
          npm install @playwright/test 
          npx playwright install
          export INCORRECT_PASSWORD=incorrectPassword
          export CORRECT_PASSWORD=secret_sauce
          npx playwright test
